apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: demo-voting-app
    name: result-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resulting-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: resulting-app-pod
      labels:
        name: resulting-app-pod
        app: demo-voting-app
    spec:
      containers:
      - name: resulting-app
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80
        
