apiVersion: v1
kind: Pod
metadata:
  name: resulting-app-pod
  labels:
    name: resulting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: resulting-app
      image: kodekloud/examplevotingapp_result:v1
      ports:
       - containerPort: 80